### ISSUE TITLE
Support Django 1.8

### ISSUE THREAD

**Issue by smcoll** [mcueto/djangorestframework-auth0#29]
Would it be too much to support Django 1.8?  Installation requires 1.10+.  1.8 is an LTS under extended support for another year.

**Comment by mcueto** [comment]
we could do this, but for this we would need to create a custom user Model for every project. This is because the username lenght in django <=1.9 was only 30 and sometimes the username retrieved by auth0 is more than that

**Comment by smcoll** [comment]
i see.  How about swappable methods for 1) looking up a user and 2) creating a new user?  In my case, i'm saving the Auth0 user ID in a Postgres hstore field anyway (not using it as the user's natural key).

**Comment by mcueto** [comment]
I could create it if you need it, the only thing i need is time! hahahahah if you don't have problem with that :)

**Comment by smcoll** [comment]
@mcueto i appreciate that, but don't worry about it.  We rolled our own implementation.

**Comment by mcueto** [comment]
ok ;) i close the issue then. however i will try to support django versions lower than 1.8 in the future.


Thanks
