### ISSUE TITLE
Is the RS256 Algorithm supported?

### ISSUE THREAD

**Issue by ryanuc** [mcueto/djangorestframework-auth0#30]
I'm using this library successfully with an Auth0 Client using HS256 algorithm.

However, for various reasons we need to use the RS256 algorithm instead.  

Is RS256 tested / supported?  In order to use RS256 I'd need to store my public key / certificate locally, however I can't find reference on how to this in this package.

I can dig into rest_framework_jwt for more info, however I thought I'd ask the question here in the instance it has already been solved.

**Comment by mcueto** [comment]
I'm working on it right now, it will be finished on next monday

**Comment by mcueto** [comment]
Version 0.4.5 released with this change! ;)

***you can follow the readme from the [sample project][sample]***

[sample]:https://github.com/mcueto/djangorestframework-auth0_sample

Nice week for you
