### ISSUE TITLE
Set audience

### ISSUE THREAD

**Issue by mrcmoresi** [mcueto/djangorestframework-auth0#31]
Hi @mcueto i've a question about audience, should i set it on my settings.py?
one more thing, in your docs, you define 'AUTH0_ALGORITHM' inside the auth0 dictionary, but it should be inside  of Clients.
Can i follow you on twitter or other?

Esp> Tengo que configurar en algun lado del proyecto de DRF el campo audience que me brinda auth0.
AUTH0_ALGORITHM me tira un error donde esta configurado ahora, si lo dejo adentro de un client funciona.
Saludos

**Comment by mcueto** [comment]
Gracias por el aviso! claro claro en el punto 3 está mal, lo arreglaré a la brevedad :)

No olvides darle me gusta y contribuir al proyecto si es que puedes. Twitter aún no tengo(debido a que no tengo tiempo para poder mantenerlo) pero pronto me haré uno ;) te aviso

**Comment by mcueto** [comment]
mrcmoresi, i will create a twitter soon, i will tell you when i do it.

Nice weekend
