### ISSUE TITLE
Not getting authentication to verify token correctly

### ISSUE THREAD

**Issue by ToniTang** [mcueto/djangorestframework-auth0#33]
Hello! I'm super happy you made this awesome tool and I'm super excited to use it, however after trying for a little I can't seem to get my tokens that were granted by Auth0 to work.

The part that confuses me a little is where you say the 'aud' claim in the token must be the same as the client id, however my access tokens generated from Auth0 use the 'aud' claim to specify API identifiers, not the client id.

I'm using my non-interactive client created through Auth0 with the signing certificate for RS256 authentication, I also already followed your sample project but did not manage to get the configuration to work.

Thanks again!

**Comment by ToniTang** [comment]
Figured it out, ended up just using my API identifier as my client ID! I had the wrong client in mind.

**Comment by mcueto** [comment]
Excelent!!! thanks for use this tool :)
