### ISSUE TITLE
Auth0 token validation as Django Middleware

### ISSUE THREAD

**Issue by bholagabbar** [mcueto/djangorestframework-auth0#35]
Thanks for the library and support, but it's is heavily outdated and non-functional. I have taken help from the official auth-0 docs at https://auth0.com/docs/quickstart/backend/python and added support for Auth0 token validation as Django Middleware. You can see the post at https://community.auth0.com/questions/8640/auth0-token-validation-as-django-middleware

**Comment by mcueto** [comment]
I will evaluate if implements it in the package.

Thank you
