### ISSUE TITLE
How can I save the user profile?

### ISSUE THREAD

**Issue by LeCoupa** [mcueto/djangorestframework-auth0#39]
When the user is authenticated for the first time, it creates him.

![pasted image at 2017_10_18 05_57 pm](https://user-images.githubusercontent.com/1658644/31770501-186185d8-b4d0-11e7-9274-c7f9047eebaa.png)

But how can I also save the profile? I am sending the `access_token` but the profile information seems to be contained in the `id_token`.

**Comment by Calion54** [comment]
Hi,

If the question is still relevant, you can use the api management v2 (https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id) which allows you to get full information about the users.
