### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by jayvdb** [mcueto/djangorestframework-auth0#44]
GitHub is missing a tag for 0.4.6.

As a packager, I need a tag if the PyPI sdist doesnt include the tests, so that I can fetch the correct test suite from somewhere, in order to run the tests to validate the packaging is correct.

**Comment by jayvdb** [comment]
Ah, there is only a dummy test, no real tests.  Still GitHub tags are useful for other things ;-)

**Comment by mcueto** [comment]
Hi @jayvdb thanks for contribute to this project. I will reactivate the development of this package so tests and other features will be implemented.

There is a newer version of this package(0.5.0) available to install from PyPi.

I will close this issue, if you're interested on this project please stay tuned. :eye:

**Comment by jayvdb** [comment]
Thanks @mcueto .  You may be interested in developments at https://github.com/Styria-Digital/django-rest-framework-jwt/issues/4 .  Specifically I suggest a requirement that the fork only tries to consider backwards compatibility with packages which have tests, so I excluded this one from my analysis because it doesn't have tests.  Even rudimentary tests covering only the most common code pathways are sufficient, because then the effort to add support is worth the investment.

I created a basic .spec file at https://build.opensuse.org/package/show/home:jayvdb:django/python-rest_framework_auth0 , but can not submit it to the main openSUSE repositories that users access without tests.
