### ISSUE TITLE
Support python 2.7

### ISSUE THREAD

**Issue by nikksbagul** [mcueto/djangorestframework-auth0#46]
Trying to install your application in Python 2.7 and getting this issue.
`Collecting rest_framework_auth0
  Using cached https://files.pythonhosted.org/packages/fe/44/8ccc0adf1b6c8f116358814b948c45a12d9971f7feef2242672b31cd6f82/rest_framework_auth0-0.5.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1v8062/rest-framework-auth0/setup.py", line 18, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-install-1v8062/rest-framework-auth0/setup.py", line 8, in get_long_description
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1v8062/rest-framework-auth0/`

**Comment by thelittlebug** [comment]
rly? python 2 is EOL

https://pythonclock.org/

**Comment by mcueto** [comment]
Closed because python 2 is dead, long live to python 3!
