### ISSUE TITLE
PyPi version out of date

### ISSUE THREAD

**Issue by markbenepass** [mcueto/djangorestframework-auth0#54]
Heads up - for anyone trying to install from PyPi: the latest version (0.5.3 from May 6, 2019) is out of date. 

Instead installing directly from Github on the latest commit works well. Using Pipenv:
rest_framework_auth0 = {git = "https://github.com/mcueto/djangorestframework-auth0.git",editable = true,ref = "47401ae8ee21b748e654677aeef3437f7d11f380"}

**Comment by mcueto** [comment]
Hi thanks Mark for the advice, i'll try to implement `python-poetry` to fix this

**Comment by mcueto** [comment]
Working on `features/poetry-implementation`

**Comment by mcueto** [comment]
Version bumped with `poetry` to `0.6.1`, built and published on pypi.

I will add info on how to use poetry when contributing to this project o another time.

Thanks @markbenepass and sorry for the delay

Closing Issue

**Comment by markbenepass** [comment]
Thanks Marcelo! I'll try it out via Pypi

**Comment by mcueto** [comment]
@markbenepass i updated the version to `0.6.4` due to python version restriction applied between `0.5.3` & `0.6.3`, now it should work with python 3.6 or upper
